### ISSUE TITLE
[G15 AE] RECOVERY partition won't show in cmd. WinRE Factory Reset won't work.

### ISSUE THREAD

**Issue by jacky-byte** [mjishnu/Fix-MyAsus-In-WinRE#1]
DiskGenius shows the RECOVERY partition with the relevant files inside, but in an elevated CMD, diskpart doesn't list the RECOVERY partition? What could be the issue?

![Screenshot 2024-06-22 084224](https://github.com/mjishnu/Fix-MyAsus-In-WinRE/assets/82864247/4d5107e3-9be8-4287-bc17-980d832e851b)
![Screenshot 2024-06-22 084144](https://github.com/mjishnu/Fix-MyAsus-In-WinRE/assets/82864247/7ce87846-03ee-46fb-891d-83560fc47ef4)

Edit:
EaseUS shows that the partition is correctly named RECOVERY, although Windows Disk Management shows it has no name. Elevated CMD shows it is called OEM, and 
`sel partition 4`
`assign letter=x`
gives me an error too.
![Screenshot 2024-06-22 091447](https://github.com/mjishnu/Fix-MyAsus-In-WinRE/assets/82864247/761461ab-3a52-41b0-bffd-75c879914596)

**Comment by mjishnu** [comment]
try and clone the partion using disk genius then try using it instead

**Comment by Kirunno** [comment]
> try and clone the partion using disk genius then try using it instead

Hello , Why did you write that the file weighs 700MB? But after importing through the program, there is only one file in xml format. Could you please update the Recovery file?
https://drive.google.com/file/d/1fb5E8ffKV2C-t8K5khG5SrvRO9xrmik5/view?usp=sharing

**Comment by Kirunno** [comment]
> try and clone the partion using disk genius then try using it instead

MyAsus is missing inside WinRE, the partition exists.

**Comment by mjishnu** [comment]
> > try and clone the partion using disk genius then try using it instead
> 
> Hello , Why did you write that the file weighs 700MB? But after importing through the program, there is only one file in xml format. Could you please update the Recovery file? https://drive.google.com/file/d/1fb5E8ffKV2C-t8K5khG5SrvRO9xrmik5/view?usp=sharing

the partition size is 700 but it doesn't contain 700mb of file atleast for me, also this is highly experimental and i have not tested

> MyAsus is missing inside WinRE, the partition exists.

try the step in the guide to link it back
